name: Deploy Application
on:
  push:
    branches:
      - main

jobs:
  create-deployment-artifacts:
    name: Create deployment aritifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and Javascript
        run: |
          npm install 
          npm run build
      - name: Configure PHP 7.4
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - name: Install composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist
